# 事务

1. 事务是什么？
   
    事务是**数据库操作的重要机制**。在数据库管理系统中，作为一个单元执行的一系列操作，操作要么全部成功，要么全部失败。
    
2. 事务具备4个特性，即原子性（Atomicity）、一致性（Consistency，事务应确保数据库的状态从一个一致状态转变为另一个一致状态。）、隔离性（Isolation）、持久性（Durability），简称ACID。
3. 适用场景：
- 银行转账：从一个账户扣钱，从另一个账号加钱
- 订单处理：创建订单和减少库存
4. 不同隔离级别（控制事务之间的并发）

- Read Uncommitted(读未提交)：所有问题都可能发生，一般不采用
- Read Committed (读已提交)：比较低的隔离级别，只能避免脏读
- Repeated Read(可重复读)：避免了脏读和可重复读，但是还是不可避免地会出现幻读
- Serializable （可串行化）：级别太高，会影响性能，所以也不太用。
- 一般来说采用可重复读避免绝大多数问题

5. 可能发生的错误方式（在并发操作中，多个事务访问同一数据时会发生冲突。数据库提供不同的隔离级别来控制事务之间的并发）

- 脏读：脏读是指一个事务读取了另一个事务未提交的数据。假设事务A更新了一条记录但尚未提交，事务B读取了该未提交的更新值。如果事务A随后回滚，这意味着事务B读取的数据是无效的，这就是所谓的“脏数据”。(这就类似于一个人事情还没做好，另一个人就用结果继续做事了。这样就很容易出现不一致。)
- 不可重复读：在同一事务中，前后两次读取同一记录，结果却不同。导致这一问题的原因是，在两次读取之间，另一个事务对该记录进行了更新并提交了。update
- 幻读：同一事务中，前后两次查询的结果集不同。通常发生在一个事务中执行了查询，然后另一个事务插入或删除了记录，使得前一个事务在再次执行相同的查询时结果集发生了变化。
- 在理解上，这两个错误方式是一件事情，只是发生的方式不一样。不可重复读关注的是同一条记录的数据变化，幻读关注的是记录的增减，即受影响的整个记录集。

6. 如何使用事务？

- 在service层面上加上@Transactional
- 内部的处理逻辑
  
    ![image-20240828202544637](https://cdn.jsdelivr.net/gh/stoneBuild29/MyPictures@main/upload/image-20240828202544637.png)

7. 最难理解的部分，像一窝粥，趁热喝了吧

**问题所在**： 在一个批量任务里（假设包含1000个任务），前面的999个任务都非常顺利、漂亮、完美且成功地执行了，然而最后一个任务非常“悲催”地失败了。这时候，Spring对着前面999个成功执行的任务说：“兄弟们，我们有一个任务失败了，现在需要全体恢复原状！”那咋整？

**目的**：当一个事务被另一个事务调用的时候，如何处理事务之间的关系

**解决方式**：事务传播行为进行界定，常用的是 REQUIRED、REQUIRED_NEW和NESTED。**这个专属的枚举类会设置不同的传播行为策略，外部和内部的关系。**

REQUIRED: 如没有，就新建；如存在，就加入这个事务中。

REQUIRED_NEW:如没有，就新建；如存在，则挂起这个事物，新建事务。

NESTED:如没有，就新建；如果有，就嵌套。在嵌套事务内执行（这个比较难理解）

- 外部事务和嵌套事务共用一个数据库连接，但会有单独的保存点
- 回滚行为：分为嵌套事务和外部事务。**如嵌套事务回滚，则滚回到实物开始设置的保存点。如外部事务回滚，则内外都变化。**

**分析和测试**：

- REQUIRED

```java
#这是一个service的实现方法，分别定义了两个方法的实现。内部是一样的方法，插入一个用户，且事务传播行为是
REQUIRED。两个方法的区别是一个正常进行，另外一个是正常进行，然后跳出异常。（不知为什么这么设计
@Service
public class UserServiceImpl extends ServiceImpl<UserMapper, User> implements UserService{

		@Autowired
		private UserMapper userMapper;
		
		@Override
		@Transactional(propagation = Propagation.REQUIRED)
		public void addWithRequired(User user){
		
				mapper.insert(user);
		
		}
		
		@Override
		@Transactional(propagation = Propagation.REQUIRED)
		public void addWithRequiredAndException(User user){
				mapper.insert(user);
				throw new RuntimeException();
		}
}
```

```java
@Slf4j
@Service
public class TransactionalServiceImpl implements TransactionService{

		@Autowired
		private UserService userService;
		
		//在事务的实现中使用用户模块的实现
		@Override
		public void noTransaction_required_required_externalException(){
				User xiaoShui = new User().setName("小水");
				User xiaoJing = new User().setName("小镜");
				
				userService.addWithRequired(xiaoShui);
				userService.addWithRequired(xiaoJing);
				
				throw new RuntimeException();
		}
		//这个外部没事务，程序按照顺序执行。两个人的数据都插入进去了。
		
		
		@Override
		public void noTransaction_required_reuqiredException(){
				User xiaoShui = new User().setName("小水");
				User xiaoJing = new User().setName("小镜");
				
				userService.addWithRequired(xiaoShui);
				userService.addWithRequiredAndException(xiaoJing);
		}
		//这个外部没事务，小水插入进去了，小镜因为异常跳出事务回滚，所以没有插入成功。
		//内部方法各自独立
		
		
		@Override
		@Transactional
		public void transaction_required_required_externalException(){
				User xiaoShui = new User().setName("小水");
				User xiaoJing = new User().setName("小镜");
				
				userService.addWithRequired(xiaoShui);
				userService.addWithRequired(xiaoJing);
				
				throw new RuntimeException();
		}
		//外部存在事务，因异常跳出事务回滚，两个数据均未进入数据库。
		//外部事务开启，所有内部事务均被加入外部方法的事务中。。
		
		
		@Override
		@Transactional
		public void Transaction_required_reuqiredException(){
				User xiaoShui = new User().setName("小水");
				User xiaoJing = new User().setName("小镜");
				
				userService.addWithRequired(xiaoShui);
				userService.addWithRequiredAndException(xiaoJing);
		}
		//这个外部有事务，小镜因异常跳出事务回滚，此时所有方法都处于同一个事务中
		//所以两个数据库均受影响。这种就属于有连带关系，一荣俱荣，一损俱损。
		
		
		@Override
		@Transactional
		public void transaction_required_requiredException_try(){
						
		  	User xiaoShui = new User().setName("小水");
				User xiaoJing = new User().setName("小镜");
				
				userService.addWithRequired(xiaoShui);
		
				try{
					userService.addWithRequiredAndException(xiaoJing);
				}catch (Exception e){
					log.error("发生异常，事务回滚！")
				}

		//因为异常被捕捉了，所以这个方法所在事务会被设置为rollback状态。
		//当外部方法执行完成后进行commit操作时，发现当前事务已经rollback状态了。只能听从指挥，回滚所有操作。
		
		}
		
		
}
//所以其实这几个例子就验证了，当事务的修饰是REQUIRED时，外部方法开启事务，内部方法的事务从属于
//外部事务。“牵一发而动全身”
```

- REQUIRES_NEW

```java
@Service
public class UserServiceImpl extends ServiceImpl<UserMapper, User> implements UserService{

	@Override
	@Transactional(propagation = Propagation.REQUIRES_NEW)
	public void addWithRequiredNew(User user){
		mapper.insert(user);
	}
	//内部事务，正常插入数据
	
	@Override
	@Transactional(propagation = Propagation.REQUIRES_NEW)
	public void addWithRequiredNewAndException(User user){
		mapper.insert(user);
		throw new RuntimeException();
	}
	//内部事务，插入数据，然后扔出异常

}
```

```java
@Slf4j
@Service
public class TransactionServiceImpl implements TransactionService{

		@Override
		@Transactional
		public void transaction_required_requiredNew_externalException(){
				User xiaoShui = new User().setName("小水");
				User xiaoJing = new User().setName("小镜");
				
				userService.addWithRequired(xiaoShui);
				userService.addWithRequiredNew(xiaoJing);
				throw new RuntimeException();
		}
		//小水没有插入，小镜插入成功
		
		
		@Override
		@Transactional
		public void transaction_required_requiredNew_requiredNewException(){
				User xiaoShui = new User().setName("小水");
				User xiaoJing = new User().setName("小镜");
				User shuiJing = new User().setName("水镜")；
				
				userService.addWithRequired(xiaoShui);
				userService.addWithRequiredNew(xiaoJing);
				userService.addWithRequiredNewAndException(shuiJing);
		
		}
		//小水没有插入(外部回滚)，小镜插入成功，水镜没有插入(内部回滚)
		//水镜的异常没有被处理，因此会被外部事务感知到，继而影响到小水
		
		
		@Override
		@Transactional
		public void transaction_required_requiredNewException_try(){
				User xiaoShui = new User().setName("小水");
				User xiaoJing = new User().setName("小镜");
				User shuiJing = new User().setName("水镜");
				
				userService.addWithRequired(xiaoShui);
				userService.addWithRequiredNew(xiaoJing);
				try{
					userService.addWithRequiredNewAndException(shuiJing);
				}catch(Exception ex){
					log.error("发生异常，事务回滚");
				}
	
		}
		//这个方法小水和小镜都插入成功了
		//之所以和前面不同，是因为它的事务是独立于外部事务的，所以异常被处理之后，不会影响其他事务
		
} 
```

- NESTED
  
    当外部事务的内部事务被设置为NESTED之后，内部方法会开启一个新的嵌套事务（子事务）。
    
    ```java
    @Service
    public class UserServiceImpl extends ServiceImpl<UserMapper, User> implements
    UserService{
    		@Override
    		@Transactional(propagation = Propagation.NESTED)
    		public void addWithNested(User user){
    			mapper.insert(user);
    		}
    		
    		@Override
    		@Transactional(propagation = Propagation.Nested)
    		public void addWithNestedAndException(User user){
    			mapper.insert(user);
    			throw new RuntimeException();
    		}
    }
    ```
    
    ```java
    @Slf4j
    @Service
    public class TransactionServiceImpl implements TransactionService{
    	
    	@Override
    	@Transactional
    	public void  transaction_nested_nested_externalException(){
    		User xiaoShui = new User().setName("小水");
    		User xiaoJing = new User().setName("小镜");
    		
    		userService.addWithNested(xiaoShui);
    		userService.addWithNested(xiaoJing);
    		
    		throw new RuntimeException();
    	}
    	//外部事务开启事务，内部方法开启各自的子事务
    	//外部事务发生异常，大回滚，内部事务跟着一起回滚，两条数据都没有插入
    
    @Override
    @Transactional
    public void transaction_nested_nestedException(){
    		User xiaoShui = new User().setName("小水");
    		User xiaoJing = new User().setName("小镜");
    		
    		userService.addWithNested(xiaoShui);
    		userService.addWithNestedAndException(xiaoJing);
    }
    //外部方法开启事务，内部方法开启自己的子事务
    //小镜的方法发生异常，内部进行回滚；而且没有异常处理，会被外部方法感知到
    //小水的方法跟着外部事务进行回滚，所以也没有插入
    
    @Override
    @Transactional
    public void transaction_nested_nestedException_try(){
    
    	User xiaoShui = new User().setName("小水");
    	User xiaoJing = new User().setName("小镜");
    	User shuiJing = new User().setName("水镜")；
    	
    	
    	userService.addWithRequired(xiaoShui);
    	userService.addWithNested(xiaoJing);
    	try{
    			userService.addWithNestedAndException(shuiJing);
    	} catch (Exception ex){
    		log.error("发生异常，事务回滚", ex);
    	}
    }
    
    //小水和小镜插入了，水镜没有插入
    //外部方法开启事务，小水和水镜开启各自的子事务，小镜加入外部的子事务
    //水镜发生异常且被处理，其他正常处理
    
    }
    ```
    
8. 理解了好久

- 就是在一个事务中，只要有异常，这个事务就会受到影响。这话咋理解？

这句话是指在一个事务中，如果任何部分发生了异常（例如，抛出异常或运行错误），整个事务就会受到影响。具体表现为：

1. **回滚**：当事务中的某个操作出现异常时，通常会导致整个事务回滚到最初状态。事务中的所有操作都不会被持久化到数据库中，就像这个事务从未执行过一样。这是事务的 **原子性** 原则，即要么全部执行成功，要么全部不执行。
2. **一致性**：异常的出现可能导致数据处于不一致状态。因此，事务回滚有助于保持数据的一致性，确保数据库不会因为部分操作失败而存留不完整或错误的数据。
3. **传播影响**：事务内部的异常不仅会影响引发异常的操作，还会影响事务中的其他操作，即使这些操作本身没有问题。

举个例子，如果你在一个事务中先插入了一条记录，然后更新另一条记录，假设在更新时发生了异常，那么插入的记录也会被回滚，因为整个事务都受到异常的影响。

因此，在事务中处理异常时，开发人员通常会采取一定的措施来捕获和处理异常，以避免不必要的回滚或者确保适当的回滚行为。